receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:8888"

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ debug ]
    metrics:
      receivers: [ otlp ]
      exporters: [ debug, prometheus ]
#    logs:
#      receivers: [ otlp ]
#      exporters: [ debug ]
