receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
  hostmetrics:
    root_path: /hostfs
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
      disk:
      load:
      filesystem:
        exclude_mount_points:
          mount_points:
            - /dev/*
            - /proc/*
            - /sys/*
            - /run/k3s/containerd/*
            - /var/lib/docker/*
            - /var/lib/kubelet/*
            - /snap/*
          match_type: regexp
        exclude_fs_types:
          fs_types:
            - autofs
            - binfmt_misc
            - bpf
            - cgroup2
            - configfs
            - debugfs
            - devpts
            - devtmpfs
            - fusectl
            - hugetlbfs
            - iso9660
            - mqueue
            - nsfs
            - overlay
            - proc
            - procfs
            - pstore
            - rpc_pipefs
            - securityfs
            - selinuxfs
            - squashfs
            - sysfs
            - tracefs
          match_type: strict
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
      network:
      paging:
      processes:
      process:
        mute_process_exe_error: true
        mute_process_io_error: true
        mute_process_user_error: true

processors:
  resource:
    attributes:
      - key: service.name
        action: insert
        value: "demo-bot"
      - key: loki.resource.labels
        action: insert
        value: "service.name"
  batch:
    { }

exporters:
  prometheus:
    endpoint: ":8889"
    namespace: "promeotel"
  debug:
    verbosity: detailed
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  otlp:
    endpoint: "tempo:55680"
    tls:
      insecure: true

#processors:
#  batch:
#    timeout: 5s
#    send_batch_size: 1024
#    send_batch_max_size: 1024
#    send_batch_min_size: 1
#    send_batch_count: 1000
#    send_batch_timeout: 5s

#extensions:
#  health_check:
#  pprof:
#    endpoint: "1888"


service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug, otlp ]
    metrics:
      receivers: [ otlp, hostmetrics ]
      processors: [ batch ]
      exporters: [ debug, prometheus ]
    logs:
      receivers: [ otlp ]
      processors: [ resource, batch ]
      exporters: [ debug, loki ]
