services:
  bot1:
    image: ${BOT1_DOCKER_IMAGE}:latest
    container_name: ${BOT1_REPOSITORY_NAME}-bot1
    restart: unless-stopped
    env_file:
      - ./bots/bot1/.env
    networks:
      - botnet

  ui:
    build: ./ui
    container_name: ui-service
    ports:
      - "3000:3000"
    environment:
      - BOT_NAMES=${KNOWN_BOTS}
    depends_on:
      - bot
      - nginx
    networks:
      - botnet

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/static:/usr/share/nginx/html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./bots:/etc/nginx/bots:ro
      - ./logs:/var/log/nginx
#    depends_on:
#      - bot
    networks:
      - botnet

networks:
  botnet:
    driver: bridge
