services:
  bot1:
    image: ${BOT1_DOCKER_IMAGE}:latest
    container_name: ${BOT1_REPOSITORY_NAME}-bot1
    restart: unless-stopped
    env_file:
      - ./bots/bot1/.env
    volumes:
      - ./bots/bot1/logs:/app/logs
    networks:
      - botnet

  log-server:
    build: ./log-server
    ports:
      - "8090:8090"
    volumes:
      - ./bots:/bots:ro
    depends_on:
      - bot1
    networks:
      - botnet
    environment:
      - LOGS_ROOT=/bots

  log-ui:
    build:
      context: ./ui
      args:
        VITE_KNOWN_BOTS: ${KNOWN_BOTS}
    container_name: logs-ui
    restart: unless-stopped
    depends_on:
      - bot1
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    networks:
      - botnet

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/static:/usr/share/nginx/html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./bots:/etc/nginx/bots:ro
      - ./logs:/var/log/nginx
#    depends_on:
#      - bot
    networks:
      - botnet

networks:
  botnet:
    driver: bridge
