services:
  bot:
    image: ladut/telegram-bot:latest
    container_name: telegram-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:8080/actuator/health | grep '\"status\":\"UP\"'" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    volumes:
      - ./VERSION:/app/VERSION
    networks:
      - botnet

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./VERSION:/etc/nginx/VERSION:ro
      - ./status.json:/etc/nginx/status.json:ro
      - ./logs/deploy.log:/var/log/nginx/deploy.log:ro
      - ./logs:/var/log/nginx
#    depends_on:
#      - bot
    networks:
      - botnet

networks:
  botnet:
    driver: bridge
