services:
  bot1:
    image: ${BOT1_DOCKER_IMAGE}:latest
    container_name: ${BOT1_REPOSITORY_NAME}-bot1
    restart: unless-stopped
    env_file:
      - ./bots/bot1/.env
    networks:
      - botnet

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/static:/usr/share/nginx/html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./bots/bot1/VERSION:/etc/nginx/VERSION:ro
      - ./bots/bot1/status.json:/etc/nginx/status.json:ro
      - ./bots/bot1/logs/deploy.log:/var/log/nginx/deploy.log:ro
      - ./logs:/var/log/nginx
#    depends_on:
#      - bot
    networks:
      - botnet

networks:
  botnet:
    driver: bridge
