services:
  bot:
    image: dladutsko/telegram-bot:latest
    container_name: telegram-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:8080/actuator/health | grep '\"status\":\"UP\"'" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - botnet

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./logs:/var/log/nginx
    depends_on:
#      - bot
      - webhook-listener
    networks:
      - botnet
  
  webhook-listener:
    build: ./webhook
    container_name: github-webhook-listener
    restart: unless-stopped
    environment:
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/deploy/app:/app
    working_dir: /app
    networks:
      - botnet

networks:
  botnet:
    driver: bridge
