services:
  bot:
    image: ladut/telegram-bot:latest
    container_name: telegram-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    networks:
      - botnet

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/static:/usr/share/nginx/html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./VERSION:/etc/nginx/VERSION:ro
      - ./status.json:/etc/nginx/status.json:ro
      - ./logs/deploy.log:/var/log/nginx/deploy.log:ro
      - ./logs:/var/log/nginx
#    depends_on:
#      - bot
    networks:
      - botnet

networks:
  botnet:
    driver: bridge
