version: '3.9'

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"
    tag: "{{.Name}}"

volumes:
  grafana_data:
  tempo_data:
  loki_data:
  prometheus_data:

networks:
  otel-monitor:
    external: true
  traefik-public:
    external: true

services:
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning/datasources/all-datasources.yml:/etc/grafana/provisioning/datasources/all-datasources.yml
    env_file:
      - ./monitoring/grafana/config.monitoring
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.${DOMAIN_NAME}
    networks:
      - traefik-public
      - otel-monitor
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=traefik-public"
        - "traefik.constraint-label=traefik-public"

        - "traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN_NAME}`)"
        - "traefik.http.routers.grafana.entrypoints=https"
        - "traefik.http.routers.grafana.tls.certresolver=le"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    logging: *logging

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otel-config.yml" ]
    ports:
#      - "4317:4317"      # OTLP gRPC
      - "4318:4318"      # OTLP http receiver
      - "8889:8889"      # Prometheus metrics
    volumes:
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./monitoring/otel/otel-collector-config.yml:/etc/otel-config.yml
    networks:
      - otel-monitor
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    logging: *logging

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo/tempo.yml" ]
    volumes:
      - tempo_data:/var/tempo
      - ./monitoring/tempo:/etc/tempo
    ports:
      - "3200:3200"
      - "55680:55680"  # OTLP gRPC for traces
    networks:
      - otel-monitor
    logging: *logging

  loki:
    image: grafana/loki:latest
    volumes:
      - loki_data:/loki
    ports:
      - "3100:3100"
    networks:
      - otel-monitor
    logging: *logging

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - prometheus_data:/prometheus
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - otel-monitor
    logging: *logging
