apiVersion: 1

deleteDatasources:
  - name: OpenTelemetry Collector
    orgId: 1

datasources:
  - name: OpenTelemetry Collector
    type: prometheus
    access: proxy
    orgId: 1
    url: http://otel-collector:8888
    isDefault: true
    editable: true
    jsonData:
      httpMethod: GET
