apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://monitoring_prometheus:9090
    isDefault: false
    editable: true

  - name: OpenTelemetry Collector
    type: prometheus
    access: proxy
    url: http://otel-collector:8888
    isDefault: true
    editable: true
    jsonData:
      httpMethod: GET
